### PR TITLE
Hello Bryant, some last changes to support a couple of new methods.

### PR DESCRIPTION
**Pull request by tufla**

### CODE REVIEW

**Comment by torrenegra** [comment]
Thank you!

_@torrenegra_ http://twitter.com/torrenegra
Tech Co-founder and CEO
http://voicebunny.com
+1 212 203 3002

On Sat, Jan 7, 2012 at 10:36 AM, Henry Canastero <
reply@reply.github.com

**Comment by torrenegra** [comment]
Hello friends and colleagues! I want to tell you about our new, awesome
startup: http://VoiceBunny.com

With VoiceBunny you get fast, professional voiceovers for any type of
project. You determine the price or royalties. Use our site or our API and
get access to 100k+ talents and 50+ languages.

VoiceBunny can be used for advertising, autopodcasting, TV, radio,
videogames, elearning, audiobooks, ebooks, phone systems, translations,
mobile apps, audio guides, research, etc. Our goal is to become the
Amazon, Getty, and Etsy of the spoken word.

I've assembled a talented team of overachievers and a great team of
advisors, some of them brought over from Voice123. We are hiring locally 
and internationally. We'll be raising capital soon so that we can, to quote 
Jeff Bezos, "grow, big, fast"!

AVC.com is currently "autopodcasted" via the VoiceBunnyAPI: 
http://www.avc.com/a_vc/2012/02/feature-friday-listen-to-this-blog.html

Please help us by spreading the word to all your friends! Thank you! :)

@torrenegra
Co-founder and CEO
- 1 212-203-3002

P.S. If you'd like me to send you periodic updates about the progress
of VoiceBunny, please let me know.
 You are receiving this message because we are friends or business contacts. Feel free to unsubscribe from this list. You won't be hurt my feelings. I promise. 
[14]Unsubscribe.
 VoiceBunny
902 Broadway
4th Floor
New York, NY 10010 

```
14. http://torrenegra.us2.list-manage1.com/unsubscribe?u=0e6635678bac2d3bf467ca7ce&id=e650d6596f&e=e465ffac83&c=6650c83489
```

**Comment by torrenegra** [comment]
## *\* We have removed your email address from our list.

We're sorry to see you go.

Was this a mistake? Did you forward one of our emails to a friend, and they clicked the unsubscribe link not realizing they were in fact unsubscribing you from this list? If this was a mistake, you can re-subscribe at:
Subscribe (http://torrenegra.us2.list-manage1.com/subscribe?u=0e6635678bac2d3bf467ca7ce&id=e650d6596f)
For questions or comments, please contact us at:
alex@torrenegra.com (mailto:alex@torrenegra.com)

**Comment by sansmischevia** [comment]
confused..

**Pull request closed without merging**
